import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { BrandLogo } from "@/components/BrandLogo";
import { ArrowRight, Check, DatabaseZap, GitBranch, LineChart, LockKeyhole, MessageCircleMore, Orbit, ScanSearch, Send, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const agents = [
  { number: "01", icon: Send, title: "Outreach Agent", detail: "Finds the right people, applies precise filters, and turns relevant audience lists into considered campaigns.", tags: ["Discover", "Filter", "Reach"] },
  { number: "02", icon: MessageCircleMore, title: "Conversation Agent", detail: "Classifies replies, drafts on-brand answers from your approved knowledge, and knows when to escalate.", tags: ["Classify", "Respond", "Escalate"] },
  { number: "03", icon: Sparkles, title: "Reply & Content Agent", detail: "Builds X presence through context-aware drafts and original content that remains under your review.", tags: ["Monitor", "Draft", "Approve"] },
];

const pricing = [
  { name: "Starter", price: "$99", note: "For disciplined outbound", included: ["Core outreach workspace", "Reply & content drafts", "Safety controls"] },
  { name: "Growth", price: "$299", note: "For full funnel operations", included: ["Outreach + conversation agents", "Lead intelligence", "CRM and funnel analytics"], featured: true },
  { name: "Pro", price: "$599", note: "For scaled growth systems", included: ["Multiple X accounts", "Advanced targeting", "Lead intelligence + automation"] },
  { name: "Enterprise", price: "Custom", note: "For tailored operations", included: ["Custom agent design", "Team workflows", "Priority support"] },
];

export default function Home() {
  const [, setLocation] = useLocation();
  const enterWorkspace = () => setLocation("/signin");

  return <div className="min-h-screen overflow-hidden bg-[#0d1712] text-[#f5f0df]"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_64%_8%,rgba(232,225,197,.16),transparent_29%),radial-gradient(circle_at_18%_28%,rgba(94,128,97,.16),transparent_22%)]" /><header className="relative z-20 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={() => setLocation("/")} className="flex items-center gap-2.5"><BrandLogo className="size-9 rounded-[10px]" /><span className="font-[Manrope] text-[15px] font-bold tracking-tight">twin3<span className="text-[#e8e1c5]">.ai</span></span></button><nav className="hidden items-center gap-7 text-sm text-[#acb9aa] md:flex"><a href="#agents" className="transition-colors hover:text-[#f5f0df]">Agents</a><a href="#system" className="transition-colors hover:text-[#f5f0df]">System</a><a href="#pricing" className="transition-colors hover:text-[#f5f0df]">Pricing</a></nav><div className="flex items-center gap-3"><button onClick={enterWorkspace} className="hidden text-sm text-[#d3d9cf] transition-colors hover:text-[#f5f0df] sm:block">Sign in</button><Button onClick={enterWorkspace} className="button-press rounded-xl bg-[#e8e1c5] px-4 text-sm font-semibold text-[#20362b] hover:bg-[#f2ecd6]">Build your pipeline <ArrowRight className="ml-1.5 size-4" /></Button></div></header>

    <main className="relative"><section className="grid-surface relative mx-auto max-w-7xl px-5 pb-20 pt-16 lg:px-8 lg:pb-32 lg:pt-24"><div className="absolute left-[5%] top-20 h-80 w-80 rounded-full bg-[#e8e1c5]/10 blur-[110px]" /><div className="relative grid items-center gap-14 lg:grid-cols-[1.02fr_.98fr]"><div className="reveal max-w-2xl"><Badge className="border-[#e8e1c5]/20 bg-[#e8e1c5]/[0.08] px-3 py-1 text-[10px] font-medium uppercase tracking-[.17em] text-[#f5f0df] hover:bg-[#e8e1c5]/[0.08]"><span className="mr-2 size-1.5 rounded-full bg-[#e8e1c5]" />AI growth infrastructure for Web3</Badge><h1 className="mt-7 font-[Manrope] text-5xl font-bold leading-[.98] tracking-[-.065em] text-[#f5f0df] sm:text-6xl lg:text-7xl">Your growth team,<br /><span className="bg-gradient-to-r from-[#d9ecd4] via-[#e8e1c5] to-[#9fbd9d] bg-clip-text text-transparent">made operational.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-[#acb9aa] sm:text-lg">Twin3 Growth Agent finds the right people, starts thoughtful conversations, and turns X activity into measurable pipeline. This is an always-on business development system—not another content tool.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Button onClick={enterWorkspace} size="lg" className="button-press h-12 rounded-xl bg-[#e8e1c5] px-6 font-semibold text-[#20362b] hover:bg-[#f2ecd6]">Enter the workspace <ArrowRight className="ml-2 size-4" /></Button><a href="#agents" className="group flex h-12 items-center px-2 text-sm font-medium text-[#d3d9cf]"><span className="border-b border-[#95a698] pb-1 transition-colors group-hover:border-[#f5f0df] group-hover:text-[#f5f0df]">Explore the agents</span></a></div><div className="mt-12 flex flex-wrap items-center gap-x-7 gap-y-3 text-xs text-[#95a698]"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-[#9fbd9d]" />Human approval where it matters</span><span className="flex items-center gap-2"><LockKeyhole className="size-4 text-[#e8e1c5]" />Knowledge-grounded replies</span></div></div>
      <div className="reveal [animation-delay:100ms]"><div className="relative mx-auto max-w-[540px] rounded-[1.6rem] border border-[#e8e1c5]/10 bg-[#17251d]/90 p-3 shadow-[0_34px_120px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="absolute -right-10 -top-10 size-44 rounded-full bg-[#e8e1c5]/15 blur-3xl" /><div className="relative overflow-hidden rounded-[1.15rem] border border-[#e8e1c5]/10 bg-[#112018]"><div className="flex items-center justify-between border-b border-[#e8e1c5]/10 px-5 py-3.5"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-[#e8e1c5]" /><span className="text-xs font-medium text-[#d3d9cf]">Growth command center</span></div><span className="mono text-[10px] text-[#95a698]">LIVE / SAFE</span></div><div className="p-5"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Today’s activity</p><p className="mt-2 text-2xl font-semibold tracking-tight">Every signal, connected.</p></div><div className="rounded-lg bg-[#9fbd9d]/10 px-2.5 py-1 text-[10px] font-medium text-[#d9ecd4]">Within limits</div></div><div className="grid grid-cols-3 gap-2.5"><Metric label="Outreach" value="137" tint="forest" /><Metric label="Replies" value="24" tint="ivory" /><Metric label="Qualified" value="08" tint="sage" /></div><div className="mt-5 rounded-xl border border-[#e8e1c5]/10 bg-[#e8e1c5]/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-medium text-[#d3d9cf]">Active campaign</span><span className="text-[10px] text-[#e8e1c5]">AI Founders</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#e8e1c5]/10"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-[#9fbd9d] to-[#e8e1c5]" /></div><div className="mt-3 flex justify-between text-[10px] text-[#95a698]"><span>320 contacted</span><span>47 replies</span><span>12 qualified</span></div></div><div className="mt-4 flex items-center gap-3 rounded-xl border border-[#e8e1c5]/10 bg-[#e8e1c5]/[.04] p-3"><div className="flex size-8 items-center justify-center rounded-lg bg-[#e8e1c5]/10"><Sparkles className="size-4 text-[#e8e1c5]" /></div><p className="text-[11px] leading-4 text-[#acb9aa]">Conversation Agent surfaced <span className="font-medium text-[#f5f0df]">3 high-intent opportunities</span> for human follow-up.</p></div></div></div></div></div></div></section>

    <section className="relative border-y border-white/[0.07] bg-white/[0.018] py-5"><div className="container flex flex-wrap items-center justify-center gap-x-10 gap-y-2 text-center text-[11px] font-medium uppercase tracking-[.16em] text-slate-500"><span>Find</span><ArrowRight className="size-3 text-indigo-300" /><span>Engage</span><ArrowRight className="size-3 text-indigo-300" /><span>Converse</span><ArrowRight className="size-3 text-indigo-300" /><span>Qualify</span><ArrowRight className="size-3 text-indigo-300" /><span>Escalate</span><ArrowRight className="size-3 text-indigo-300" /><span>Measure</span></div></section>

    <section id="agents" className="container relative py-24 lg:py-32"><div className="max-w-2xl"><p className="eyebrow">The agent system</p><h2 className="mt-4 font-[Manrope] text-3xl font-bold tracking-[-.04em] text-white sm:text-4xl">Purpose-built agents for the complete growth loop.</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">Each Twin3 agent owns a distinct part of the funnel and shares the context needed to turn every interaction into a better next action.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{agents.map((agent, i) => <article key={agent.title} className="glass-card group relative overflow-hidden rounded-2xl p-6 transition-transform duration-200 hover:-translate-y-1"><div className="absolute right-4 top-4 mono text-xs text-slate-600">{agent.number}</div><div className="flex size-11 items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.04] text-indigo-200"><agent.icon className="size-5" /></div><h3 className="mt-9 font-[Manrope] text-xl font-bold tracking-tight text-white">{agent.title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-slate-400">{agent.detail}</p><div className="mt-7 flex gap-2">{agent.tags.map((tag) => <span key={tag} className="rounded-md bg-white/[0.05] px-2 py-1 mono text-[9px] uppercase tracking-[.1em] text-slate-400">{tag}</span>)}</div><div className="mt-6 h-px bg-gradient-to-r from-indigo-400/40 to-transparent" /></article>)}</div></section>

    <section id="system" className="container pb-24 lg:pb-32"><div className="grid overflow-hidden rounded-[1.8rem] border border-white/[0.08] bg-[#15172c] lg:grid-cols-[.9fr_1.1fr]"><div className="relative p-8 lg:p-11"><div className="absolute -left-12 bottom-0 size-64 rounded-full bg-cyan-500/10 blur-[90px]" /><div className="relative"><p className="eyebrow">Designed for outcomes</p><h2 className="mt-4 font-[Manrope] text-3xl font-bold tracking-[-.045em] text-white">Control without compromise.</h2><p className="mt-5 max-w-md leading-7 text-slate-400">Twin3 handles repetitive growth work with rules your team defines. Sensitive, uncertain, or unapproved conversations are routed to the people who can make the right call.</p><div className="mt-9 space-y-5">{[[ShieldCheck, "Safety before volume", "Activity limits, rate-aware operation, and auto-pause controls protect your X account."], [DatabaseZap, "Your knowledge, applied", "Every agent response is grounded in an approved knowledge base—never invented product claims."], [UsersRound, "Human escalation built in", "Full context and clear reasons make handoffs useful, not disruptive."]].map(([Icon, title, text]) => <div key={String(title)} className="flex gap-4"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-indigo-400/10 text-indigo-200"><Icon className="size-4" /></div><div><p className="text-sm font-semibold text-slate-200">{String(title)}</p><p className="mt-1 text-sm leading-5 text-slate-500">{String(text)}</p></div></div>)}</div></div></div><div className="border-t border-white/[0.07] bg-[#101224] p-6 lg:border-l lg:border-t-0 lg:p-10"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">The growth loop</p><p className="mt-1 text-xs text-slate-500">Data from each interaction improves the next one.</p></div><Orbit className="size-5 text-indigo-300" /></div><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3">{[[ScanSearch,"Discover"],[Send,"Engage"],[MessageCircleMore,"Converse"],[GitBranch,"Qualify"],[UsersRound,"Escalate"],[LineChart,"Measure"]].map(([Icon, label], index) => <div key={String(label)} className="relative rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><span className="mono text-[10px] text-slate-600">0{index + 1}</span><Icon className="mt-5 size-4 text-cyan-200" /><p className="mt-3 text-xs font-medium text-slate-200">{String(label)}</p></div>)}</div></div></div></section>

    <section id="pricing" className="container pb-28 lg:pb-36"><div className="text-center"><p className="eyebrow">Post-validation pricing</p><h2 className="mt-4 font-[Manrope] text-3xl font-bold tracking-[-.045em] text-white sm:text-4xl">Start with the growth system you need.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{pricing.map((tier) => <div key={tier.name} className={`relative rounded-2xl border p-6 ${tier.featured ? "border-indigo-300/35 bg-gradient-to-b from-indigo-400/[0.13] to-[#181a30] shadow-[0_18px_55px_rgba(99,102,241,.12)]" : "border-white/[0.08] bg-white/[0.025]"}`}>{tier.featured && <span className="absolute -top-3 left-6 rounded-full bg-indigo-300 px-3 py-1 mono text-[9px] font-medium uppercase tracking-[.13em] text-slate-950">Most complete</span>}<p className="text-sm font-semibold text-white">{tier.name}</p><p className="mt-5 font-[Manrope] text-4xl font-bold tracking-[-.05em] text-white">{tier.price}{tier.price !== "Custom" && <span className="ml-1 text-sm font-normal tracking-normal text-slate-500">/mo</span>}</p><p className="mt-3 min-h-10 text-sm text-slate-500">{tier.note}</p><div className="my-6 h-px bg-white/[0.07]" /><ul className="space-y-3">{tier.included.map((item) => <li key={item} className="flex gap-2.5 text-xs leading-5 text-slate-400"><Check className="mt-0.5 size-3.5 shrink-0 text-cyan-200" />{item}</li>)}</ul><Button onClick={enterWorkspace} variant={tier.featured ? "default" : "outline"} className={`button-press mt-8 w-full rounded-xl ${tier.featured ? "bg-indigo-300 text-slate-950 hover:bg-indigo-200" : "border-white/10 bg-white/[0.03] text-slate-200 hover:bg-white/[0.07]"}`}>{tier.price === "Custom" ? "Talk to us" : "Get started"}</Button></div>)}</div></section>
    </main><footer className="relative border-t border-[#e8e1c5]/10 py-7"><div className="container flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#d3d9cf]"><BrandLogo className="size-5 rounded-md" />twin3.ai</div><p className="text-xs text-[#95a698]">AI growth systems for teams who value relevance over volume.</p></div></footer></div>;
}

function Metric({ label, value, tint }: { label: string; value: string; tint: "forest" | "ivory" | "sage" }) {
  const colors = { forest: "from-[#315642]/35 to-[#315642]/[.04] text-[#d9ecd4]", ivory: "from-[#e8e1c5]/20 to-[#e8e1c5]/[.04] text-[#f5f0df]", sage: "from-[#9fbd9d]/25 to-[#9fbd9d]/[.04] text-[#d9ecd4]" };
  return <div className={`rounded-lg border border-white/[0.06] bg-gradient-to-b p-3 ${colors[tint]}`}><p className="mono text-lg font-medium">{value}</p><p className="mt-1 text-[9px] uppercase tracking-[.12em] text-slate-500">{label}</p></div>;
}
