import { BrandLogo } from "@/components/BrandLogo";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowLeft, ArrowRight, LockKeyhole, ShieldCheck, X } from "lucide-react";
import { Link } from "wouter";

export default function SignIn() {
  return <main className="grid-surface flex min-h-screen items-center justify-center bg-[#0d1712] px-5 text-[#f5f0df]"><div className="w-full max-w-md rounded-[1.7rem] border border-[#e8e1c5]/10 bg-[#17251d]/95 p-7 shadow-[0_32px_100px_rgba(0,0,0,.45)] backdrop-blur-xl sm:p-9"><Link href="/" className="inline-flex items-center gap-2 text-sm text-[#acb9aa] transition-colors hover:text-[#f5f0df]"><ArrowLeft className="size-4" />Back to twin3.ai</Link><BrandLogo className="mt-9 size-12" /><p className="eyebrow mt-7">Secure workspace access</p><h1 className="mt-3 font-[Manrope] text-3xl font-bold tracking-[-.05em] text-[#f5f0df]">Enter Twin3</h1><p className="mt-3 text-sm leading-6 text-[#acb9aa]">Sign in with your Twin3 workspace account or use X to create a secure account and connect the profile your agents will operate for.</p><div className="mt-8 space-y-3"><Button onClick={() => window.location.assign("/api/x/authorize?intent=signin")} className="button-press h-12 w-full rounded-xl bg-[#e8e1c5] text-[#20362b] hover:bg-[#f2ecd6]"><X className="mr-2 size-4" strokeWidth={2.5} />Continue with X <ArrowRight className="ml-2 size-4" /></Button><Button onClick={startLogin} variant="outline" className="button-press h-12 w-full rounded-xl border-[#e8e1c5]/15 bg-[#e8e1c5]/[.04] text-[#f5f0df] hover:bg-[#e8e1c5]/[.1]">Continue with workspace sign-in</Button></div><div className="mt-7 rounded-xl border border-[#9fbd9d]/15 bg-[#9fbd9d]/[.06] p-4"><div className="flex items-center gap-2 text-xs font-semibold text-[#d9ecd4]"><ShieldCheck className="size-4" />Approval-first X access</div><p className="mt-2 text-xs leading-5 text-[#acb9aa]">Twin3 requests only the permissions needed to connect your account. Reply and content drafts remain in Draft Mode until you approve them.</p></div><p className="mt-6 flex items-center gap-2 text-[11px] text-[#95a698]"><LockKeyhole className="size-3.5" />Your X connection can be revoked anytime in Safety &amp; Controls.</p></div></main>;
}
